version: 2
updates:
  # app
  - package-ecosystem: "cargo"
    directory: "common_lib"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "function-deployer-rs"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "function-invoker-rs"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "function-report-log-processor-rs"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "function-trigger-deployer-rs"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "result-builder"
    dependency-type: "all"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "s3-uploader"
    dependency-type: "all"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "container-uploader"
    dependency-type: "all"
    schedule:
      interval: "monthly"

  # runtimes
  - package-ecosystem: "nuget"
    directory: "s3-uploader/runtimes/dotnet6/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "s3-uploader/runtimes/dotnet7_aot_on_provided_al2/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "s3-uploader/runtimes/dotnet8_aot_on_provided_al2/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "s3-uploader/runtimes/dotnet8_aot_on_provided_al2023/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "s3-uploader/runtimes/dotnet9_aot_on_provided_al2023/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "s3-uploader/runtimes/go_on_provided_al2"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "s3-uploader/runtimes/go_on_provided_al2023"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "s3-uploader/runtimes/go1x"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "s3-uploader/runtimes/graalvm_java17_on_provided_al2"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java8"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java8_al2"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java11"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java11_snapstart"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java17"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java17_snapstart"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java21"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "s3-uploader/runtimes/java21_snapstart"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "s3-uploader/runtimes/quarkus_native_on_provided_al2"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "s3-uploader/runtimes/rust_on_provided_al2"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "s3-uploader/runtimes/rust_on_provided_al2023"
    schedule:
      interval: "daily"
