# name: test

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-24.04
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install Rust toolchain
#         uses: dtolnay/rust-toolchain@stable
#       - name: Install Zig toolchain
#         uses: korandoru/setup-zig@v1
#         with:
#           zig-version: 0.10.0
#       - name: Install Cargo Lambda
#         uses: jaxxstorm/action-install-gh-release@v1.9.0
#         with:
#           repo: cargo-lambda/cargo-lambda
#           platform: linux
#           arch: x86_64
#       - name: Test
#         run: cargo test
#       - name: Build
#         run: ./build.sh
#       - name: install dependencies
#         run: |
#           cd ./result-builder && yarn install
